# Generated by Django 4.2.2 on 2023-06-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MMRUtilityApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mmrmodel",
            name="pay_proc_period",
            field=models.CharField(max_length=6),
        ),
    ]
