# Generated by Django 4.2.2 on 2023-06-09 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("MMRUtilityApp", "0002_alter_mmrmodel_pay_proc_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="mmrmodel",
            name="adj_reason",
            field=models.CharField(default="", max_length=2),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="ben_dual_partd_flg",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="clean_id",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="cur_medcd_stats",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="de_minimis",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="dem_pay_adj_rat_a",
            field=models.CharField(default="", max_length=9),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="dem_pay_adj_rat_b",
            field=models.CharField(default="", max_length=9),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="dflt_prtd_rsk_cd",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="dflt_risk",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="eghp_ind",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="enrl_src_ind",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="esrd_ind",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="esrd_msp_cd",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="frailty_ind",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="hscp_ind",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="inc_prm_sbsd_amt",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="inst_ind",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="lag_ind",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="low_inc_sbsd_cst",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="lti_flag",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="medcd_addon",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="medcd_dual_sts",
            field=models.CharField(default="", max_length=2),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="medcd_ind",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="msa_prta_rec_amt",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="msa_prtb_rec_amt",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="msa_rec_months",
            field=models.CharField(default="", max_length=2),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="msp_fct",
            field=models.CharField(default="", max_length=7),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="msp_rduc_amt_a",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="msp_rduc_amt_b",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="nhc_ind",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="ooa_ind",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="orig_dsbl_ind",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="pace_prm_addon",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="pace_shr_addon",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="part_a",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="part_b",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="pay_adj_end_dt",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="pay_adj_prta_mo",
            field=models.CharField(default="", max_length=2),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="pay_adj_prtb_mo",
            field=models.CharField(default="", max_length=2),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="pay_adj_prtd_mo",
            field=models.CharField(default="", max_length=2),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="pay_adj_strt_dt",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="pbp_seg_ind",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="pip_dcg",
            field=models.CharField(default="", max_length=2),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="pln_ben_pkg_id",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prev_dsbl_ratio",
            field=models.CharField(default="", max_length=7),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prta_cst_shr_rbt",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prta_oth_prta",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prta_risk_adj_mor",
            field=models.CharField(default="", max_length=9),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prtb_cst_shr_rbt",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prtb_oth_prta",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prtb_prm_rduc_a",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prtb_prm_rduc_b",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prtb_risk_adj_mor",
            field=models.CharField(default="", max_length=9),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prtc_bas_prm_parta",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prtc_bas_prm_partb",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prtc_fral_fct",
            field=models.CharField(default="", max_length=7),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prtd_bas_prm_amt",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prtd_cov_dap_dis",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prtd_dir_sbsd_mor",
            field=models.CharField(default="", max_length=9),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prtd_dir_sbsd_pay",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prtd_lng_trm_ind",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prtd_lng_trm_mult",
            field=models.CharField(default="", max_length=7),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prtd_low_inc_cd",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prtd_low_inc_mult",
            field=models.CharField(default="", max_length=7),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prtd_risk_adj_fct",
            field=models.CharField(default="", max_length=7),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prtd_rskadj_fct",
            field=models.CharField(default="", max_length=2),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prtd_sup_ben_a",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="prtd_sup_ben_b",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="ra_fct_typ_cd",
            field=models.CharField(default="", max_length=2),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="race_cd",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="rbt_prtd_bas_prm",
            field=models.CharField(default="", max_length=8),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="reins_sbsd_amt",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="risk_adj_age_grp",
            field=models.CharField(default="", max_length=4),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="risk_adj_fac_a",
            field=models.CharField(default="", max_length=7),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="risk_adj_fac_b",
            field=models.CharField(default="", max_length=7),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="risk_adj_rate_a",
            field=models.CharField(default="", max_length=9),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="risk_adj_rate_b",
            field=models.CharField(default="", max_length=9),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="state_county",
            field=models.CharField(default="", max_length=5),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="tot_payment",
            field=models.CharField(default="", max_length=11),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="tot_prt_a_yay",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="tot_prt_b_yay",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="tot_prtd_pay_amt",
            field=models.CharField(default="", max_length=11),
        ),
        migrations.AddField(
            model_name="mmrmodel",
            name="wrk_age_ind",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AlterField(
            model_name="mmrmodel",
            name="age_group",
            field=models.CharField(default="", max_length=4),
        ),
        migrations.AlterField(
            model_name="mmrmodel",
            name="cms_contract_id",
            field=models.CharField(default="", max_length=5),
        ),
        migrations.AlterField(
            model_name="mmrmodel",
            name="gender",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AlterField(
            model_name="mmrmodel",
            name="hic_no",
            field=models.CharField(default="", max_length=12),
        ),
        migrations.AlterField(
            model_name="mmrmodel",
            name="mbr_first_init",
            field=models.CharField(default="", max_length=1),
        ),
        migrations.AlterField(
            model_name="mmrmodel",
            name="mbr_last_name",
            field=models.CharField(default="", max_length=7),
        ),
        migrations.AlterField(
            model_name="mmrmodel",
            name="pay_proc_period",
            field=models.CharField(default="", max_length=6),
        ),
    ]
